openapi: 3.0.0
info:
  title: Social App
  description: A basic social media app
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1
    description: The local dev environment
  - url: https://lco-pro-backend-deploy-1.herokuapp.com/api/v1
    description: The production heroku environment

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer