openapi: 3.0.0
info:
  title: Social App
  description: A basic social media app
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1
    description: The local dev environment
  - url: https://lco-pro-backend-deploy-1.herokuapp.com/api/v1
    description: The production heroku environment

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /instagram:
    get:
      summary: Returns username, followers and follows
      tags:
        - instagram
      responses:
        '200': # status code
          description: Returns an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: string
                  follows:
                    type: string
    post:
      summary: Returns username, followers and follows
      tags:
        - instagram
      responses:
        '200': # status code
          description: Returns an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: string
                  follows:
                    type: string

  /{token}:  
    get:
      summary: Returns whatever is there in parameters
      tags:
        - invalid
      parameters:
        - name: token
          default: 5
          in: path
          schema:
            type: string
      responses:
        '200': # status code
          description: Returns an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  param:
                    type: string